# Generated by Django 5.1.4 on 2025-01-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquizz', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
