# Generated by Django 5.1.4 on 2025-01-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquizz', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_pictures',
            field=models.ImageField(blank=True, null=True, upload_to='question/'),
        ),
    ]
